export const workoutCopy = {
  connections: "Connections",
  tabStretch: "Stretch",
  tabMeditate: "Meditate",
  tabHistory: "History",
  focusLabel: "Focus",
  focusAll: "All",
  focusFull: "Full body",
  focusLegs: "Legs",
  focusHips: "Hips",
  focusBack: "Back",
  focusUpper: "Upper body",
  stretchCount: "stretches",
  startRoutine: "Start",
  meditation: "Meditation",
  meditationDetail: "A quiet timer. Settle in and breathe at your own pace.",
  minute: "min",
  minutes: "Minutes",
  startMeditation: "Start meditation",
  readyToSave: "Save this session to add it to your calendar.",
  soundCues: "Sound cues",
  enableSound: "Enable sound",
  storageWarning:
    "This browser could not store your timer. Keep this tab open until you save; recovery after reload may be unavailable.",
  pause: "Pause",
  resume: "Resume",
  discard: "End session",
  discardTitle: "End this session?",
  discardDetail:
    "This session will not be saved. You can start a new one whenever you’re ready.",
  finished: "Session complete",
  paused: "Paused",
  running: "In progress",
  save: "Save session",
  saving: "Saving…",
  saved: "Saved to your calendar",
  another: "Start another session",
  returnTimer: "Your workout timer · Open",
  next: "Up next",
  step: "Stretch",
  remaining: "remaining",
  log: "Log a workout",
  name: "Session name",
  sport: "Sport",
  start: "Started at",
  duration: "Duration (minutes)",
  notes: "Notes (optional)",
  local: "Saved in Coach Reachy",
  logTitle: "Record a completed workout",
  logDescription:
    "Use the start time in your current device’s timezone. Sessions appear in the Amsterdam calendar.",
  invalidTime: "Choose a completed session: its end time must be in the past.",
  recent: "Your app sessions",
  empty: "Your next small win starts here.",
  remove: "Remove session",
  removeTitle: "Remove this app session?",
  removeDetail: "This removes the session from Coach Reachy and your calendar.",
  whoop: "WHOOP workouts",
  whoopDetail: "Optional import for workouts missing from Intervals.icu.",
  whoopWellness:
    "WHOOP sleep, HRV and resting heart rate can already arrive through your Intervals.icu connection. That integration syncs wellness data, but not WHOOP workouts.",
  intervalsSettings: "Manage wellness in Intervals.icu",
  setup:
    "Direct workout import needs a separate WHOOP connection and one-time setup. You can also log missing sessions manually.",
  connect: "Connect WHOOP",
  reconnect: "Reconnect WHOOP",
  disconnect: "Disconnect WHOOP",
  disconnectTitle: "Disconnect WHOOP?",
  disconnectDetail:
    "New workouts will stop syncing. Already imported sessions stay in your calendar.",
  connected: "Connected",
  notConnected: "Not connected",
  sync: "Sync workouts",
  busy: "Working…",
  lastSync: "Last synced",
  never: "Waiting for the first sync",
  whoopError: "WHOOP could not connect. Try connecting again.",
  importRule:
    "Imports the last 90 days, then checks every 20 minutes. Matching sessions from Intervals or the app take priority. Uncertain matches stay visible.",
  imported: "Included",
  duplicate: "Matched · not counted twice",
  whoopHistory: "Recent WHOOP imports",
  source: "Source",
  appSource: "App session",
  whoopSource: "WHOOP",
  strain: "WHOOP strain",
  sports: [
    { value: "WeightTraining", label: "Fitness & strength" },
    { value: "HomeWorkout", label: "Home workout" },
    { value: "Soccer", label: "Soccer / football" },
    { value: "Run", label: "Running" },
    { value: "Ride", label: "Cycling" },
    { value: "Swim", label: "Swimming" },
    { value: "Golf", label: "Golf" },
    { value: "Tennis", label: "Tennis" },
    { value: "Walk", label: "Walking" },
    { value: "Yoga", label: "Yoga" },
    { value: "Stretching", label: "Stretching" },
    { value: "Meditation", label: "Meditation" },
    { value: "Other", label: "Other" },
  ],
};
