"use client";
import { Flag, ArrowUpRight, Check } from "lucide-react";
import Link from "next/link";
import { goalResults, thresholdHistory, type Dashboard } from "@/lib/data";
import { copy } from "@/lib/i18n";
import { metric, raceTime, pace } from "@/lib/format";
import { Card, CardHeading, Empty, Badge } from "./ui";
import { TrendChart } from "./charts";
export function GoalCard({ data, compact = false }: { data: Dashboard; compact?: boolean }) {
  const results = goalResults(data.activities); const best = results.length ? results.reduce((a,b) => a.seconds < b.seconds ? a : b) : null;
  return <Card className="goal-card"><CardHeading title={compact ? copy.overview.goalTitle : copy.insights.goal} description={compact ? copy.overview.goalDetail : copy.insights.goalDetail} action={<Flag size={17} strokeWidth={1.5} aria-hidden="true" />} /><div className="goal-body"><div className="goal-best"><span>{copy.insights.best}</span><strong>{best ? raceTime(best.seconds) : copy.common.none}</strong>{best && <small>{metric(best.distance / 1000, 2)} {copy.common.km} · {best.date}</small>}</div><div className="goal-targets">{[{ target: 1080, label: copy.insights.sub18, pace: copy.insights.goal18 }, { target: 1020, label: copy.insights.sub17, pace: copy.insights.goal17 }].map((goal, index) => <div className="goal-target" key={goal.target}><span className="goal-step">{best && best.seconds < goal.target ? <Check size={12} aria-hidden="true" /> : `0${index + 1}`}</span><div><strong>{goal.label}</strong><span>{goal.pace}</span></div>{best && <small>{best.seconds < goal.target ? copy.insights.achieved : `${raceTime(best.seconds - goal.target)} ${copy.insights.remaining}`}</small>}</div>)}</div></div>{!best && <p className="goal-empty">{compact ? copy.insights.noGoal : copy.insights.noGoalDetail}</p>}{!compact && <><TrendChart rows={results.map(r => ({ date: r.date, seconds: r.seconds }))} series={[{ key: "seconds", name: copy.insights.goalHistory }]} title={copy.insights.goalHistory} empty={copy.insights.noGoal} yFormat={raceTime} references={[{ value: 1080, label: copy.insights.sub18 }, { value: 1020, label: copy.insights.sub17 }]} height={220} /><div className="threshold-section"><h3>{copy.insights.threshold}</h3><TrendChart rows={thresholdHistory(data.activities)} series={[{ key: "pace", name: copy.insights.threshold }]} title={copy.insights.threshold} empty={copy.insights.noThreshold} yFormat={pace} height={170} /></div></>}<div className="card-footer">{compact ? <Link className="inline-link" href="/insights">{copy.common.viewDetails}<ArrowUpRight size={12} aria-hidden="true" /></Link> : copy.insights.goalNote}</div></Card>;
}
